indentation = 2 # use 0 for tabs
# insert space before a label
seperate-label = true
# insert a final newline at the end
final-newline = true

[preserve-newline]
# preserve single newlines in markup
content = true
# preserve single newline in equations
math = true

[block]
# "seperate" | "compact"  '[' and ']' on the same or seperate lines as the content
long-block-style = "seperate"

[named-argument]
space-before = false # insert a space before the ':' in named arguments
space-after = true # insert a space after the ':' in named arguments

[dictionary-entry]
space-before = false # insert a space before the ':' in dictionary entries
space-after = false # insert a space after the ':' in dictionary entries

[columns]
comma = "end-of-content" # "end-of-content" | "end-of-cell"  how to align commas in tables

[heading]
blank-lines-before = 1 # blank lines before a heading
blank-lines-after = 1 # blank lines after a heading

[columns-commands]
grid = "columns"     # format the "grid", "gridx", ... command with
gridx = "columns"    # columns specified by the named argument "columns"
table = "columns"
tablex = "columns"
